#Site Settings
title: Clint Wallingsford - IoT, Wifi, Cellular
email: cawallingsfords@gmail.com
description: Bringing together wired and wireless 
  Passionate Field Application Engineer specializing in Internet of Things (IoT) within Telecommunications.
  Exploring the intersection of connectivity, smart devices, and network infrastructure.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://boz011/github.io"
github_username: boz011
#Theme
theme: jekyll-theme-minima
author:
name: Clint Wallingsford
email: cawallingsfords@gmail.com
#Build Settings
plugins:
-jekyll-feed
-jekyll-seo-tag
