title: Clint Wallingsford - IoT in Telecom Specialist
email: cawallingsfords@gmail.com
description: >-
  Passionate Field Application Engineer specializing in Internet of Things (IoT) within Telecommunications.
  Exploring the intersection of connectivity, smart devices, and network infrastructure.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://boz011.github.io/[your-repo-name]" # the base hostname & protocol for your site, e.g. http://example.com
github_username: boz011
